# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Focus Areas
  description: Section showing focus areas with detailed cards and call-to-action buttons
  icon: 'target'
  tags:
    - Content
    - Cards
    - Focus Areas

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: '#f0f0f0'
  heading:
    heading_text: 'Our focus areas'
  subtitle:
    subtitle_text: "We're advancing research and standards to make AI agents secure, loyal, and effective advocates for consumers everywhere."
  focus_areas:
    - number: '01'
      title: 'Enabling AI agents to securely transact on behalf of consumers'
      subtitle: 'Autonomy'
      description: "Building future-proof frameworks for identity, authentication, and authorization so agents act reliably and safely on the user's behalf."
      tags: ['Security', 'Identity']
      featured_resources: ['authentic-ai-bringing-authentication-authorization-and-identity-into-the-ai-agent-world']
      color: '#c8c8c8'
      button_text: 'See how to build the future'
      button_link: '#'
    - number: '02'
      title: 'Defining duties of AI agents to consumers'
      subtitle: 'Accountability'
      description: "Establishing clear principles and legal duties that ensure AI agents remain loyal and prioritize users' interests above all."
      tags: ['Legal', 'Duty of Loyalty']
      featured_resources: []
      color: '#3a8dc7'
      button_text: 'See how the law applies'
      button_link: '#'
    - number: '03'
      title: "Ensuring agents are effective and aligned with consumers' preferences"
      subtitle: 'Alignment'
      description: 'Designing evaluation methods so agents adapt to individual goals, protect against bias, and deliver meaningful outcomes.'
      tags: ['Reliability', 'Evaluations']
      featured_resources: []
      color: '#02ad4d'
      button_text: 'See our approach to evaluations'
      button_link: '#'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  heading:
    options:
      preview:
        icon: 'short_text'
        text:
          - key: heading_text
          - Main Heading
        subtext:
          - 'Update the main section heading'
  subtitle:
    options:
      preview:
        icon: 'short_text'
        text:
          - key: subtitle_text
          - Subtitle
        subtext:
          - 'Update the subtitle description'

  focus_areas:
    options:
      preview:
        icon: 'view_module'
        text:
          - Focus Areas
        subtext:
          - 'Update the focus area cards'
  focus_areas[*].number:
    options:
      preview:
        icon: 'format_list_numbered'
        text:
          - key: number
          - Area Number
  focus_areas[*].title:
    options:
      preview:
        icon: 'title'
        text:
          - key: title
          - Area Title
  focus_areas[*].subtitle:
    options:
      preview:
        icon: 'short_text'
        text:
          - key: subtitle
          - Tab Title
  focus_areas[*].description:
    type: textarea
    options:
      preview:
        icon: 'description'
        text:
          - key: description
          - Area Description
  focus_areas[*].tags:
    type: multiselect
    options:
      values: data.tags
      value_key: title
      preview:
        icon: 'label'
        text:
          - Tags
        subtext:
          - 'Update area tags'
  focus_areas[*].featured_resources:
    type: multiselect
    options:
      values: collections.resources
      value_key: title
      preview:
        icon: 'star'
        text:
          - Featured Resources
        subtext:
          - 'Select featured resources by ID'
  focus_areas[*].color:
    type: color
    options:
      preview:
        icon: 'palette'
        text:
          - Card Color
        subtext:
          - 'Update card accent color'
  focus_areas[*].button_text:
    options:
      preview:
        icon: 'text_fields'
        text:
          - key: button_text
          - Button Text
        subtext:
          - 'Update call-to-action text'
  focus_areas[*].button_link:
    options:
      preview:
        icon: 'link'
        text:
          - Button Link
        subtext:
          - 'Update call-to-action link'
